import vgamepad as vg

# ◤↼-----------------------------------------------------------⇀◥

#   Please refrain from editing mappings here!

#   Do not relocate this file, as it may be used by the 
#   application to load the controller mappings.

#   If you want to remmap a button to another button, 
#   please use the available self.remap_button() function.
#   https://copycat.stickassist.com/documentation#buttons-4 

#   Modifying this file will may break other scripts.

# ◣↽-----------------------------------------------------------⇁◢
    
class Buttons:
    BTN_SOUTH = [vg.XUSB_BUTTON.XUSB_GAMEPAD_A, vg.DS4_BUTTONS.DS4_BUTTON_CROSS]
    BTN_EAST = [vg.XUSB_BUTTON.XUSB_GAMEPAD_B, vg.DS4_BUTTONS.DS4_BUTTON_CIRCLE]
    BTN_WEST = [vg.XUSB_BUTTON.XUSB_GAMEPAD_X, vg.DS4_BUTTONS.DS4_BUTTON_SQUARE]
    BTN_NORTH = [vg.XUSB_BUTTON.XUSB_GAMEPAD_Y, vg.DS4_BUTTONS.DS4_BUTTON_TRIANGLE]
    BTN_LEFT_SHOULDER = [vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER, vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_LEFT]
    BTN_RIGHT_SHOULDER = [vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER, vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_RIGHT]
    BTN_LEFT_TRIGGER = [98, 98]
    BTN_RIGHT_TRIGGER = [99, 99]
    BTN_BACK = [vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK, vg.DS4_BUTTONS.DS4_BUTTON_SHARE]
    BTN_OPTIONS = [vg.XUSB_BUTTON.XUSB_GAMEPAD_START, vg.DS4_BUTTONS.DS4_BUTTON_OPTIONS]
    BTN_LEFT_THUMB = [vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB, vg.DS4_BUTTONS.DS4_BUTTON_THUMB_LEFT]
    BTN_RIGHT_THUMB = [vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB, vg.DS4_BUTTONS.DS4_BUTTON_THUMB_RIGHT]
    BTN_DPAD_UP = [vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP, vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTH]
    BTN_DPAD_DOWN = [vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN, vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTH]
    BTN_DPAD_LEFT = [vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT, vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_WEST]
    BTN_DPAD_RIGHT = [vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT, vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_EAST]
    BTN_GUIDE = [vg.XUSB_BUTTON.XUSB_GAMEPAD_GUIDE, vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_PS]
    BTN_TOUCHPAD = [vg.XUSB_BUTTON.XUSB_GAMEPAD_GUIDE, vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_TOUCHPAD]

mappingXbox = {
    'buttons' : {
        "BTN_SOUTH": vg.XUSB_BUTTON.XUSB_GAMEPAD_A,
        "BTN_EAST": vg.XUSB_BUTTON.XUSB_GAMEPAD_B,
        "BTN_WEST": vg.XUSB_BUTTON.XUSB_GAMEPAD_X,
        "BTN_NORTH": vg.XUSB_BUTTON.XUSB_GAMEPAD_Y,
        "BTN_TL": vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_SHOULDER,
        "BTN_TR": vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_SHOULDER,
        "BTN_START": vg.XUSB_BUTTON.XUSB_GAMEPAD_BACK,
        "BTN_SELECT": vg.XUSB_BUTTON.XUSB_GAMEPAD_START,

        "BTN_THUMBL": vg.XUSB_BUTTON.XUSB_GAMEPAD_LEFT_THUMB,
        "BTN_THUMBR": vg.XUSB_BUTTON.XUSB_GAMEPAD_RIGHT_THUMB,
    },
    'hats': {
        'ABS_HAT0X': {
            -1: vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_LEFT,
            1: vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_RIGHT,
        },
        'ABS_HAT0Y': {
            -1: vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_UP,
            1: vg.XUSB_BUTTON.XUSB_GAMEPAD_DPAD_DOWN,
        }
    }
}

mappingDS4 = {
    'buttons' : {
        0: vg.DS4_BUTTONS.DS4_BUTTON_CROSS,
        1: vg.DS4_BUTTONS.DS4_BUTTON_CIRCLE,
        2: vg.DS4_BUTTONS.DS4_BUTTON_SQUARE,
        3: vg.DS4_BUTTONS.DS4_BUTTON_TRIANGLE,
        4: vg.DS4_BUTTONS.DS4_BUTTON_SHARE,
        5: vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_PS,
        6: vg.DS4_BUTTONS.DS4_BUTTON_OPTIONS,
        
        7: vg.DS4_BUTTONS.DS4_BUTTON_THUMB_LEFT,
        8: vg.DS4_BUTTONS.DS4_BUTTON_THUMB_RIGHT,

        9: vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_LEFT,
        10: vg.DS4_BUTTONS.DS4_BUTTON_SHOULDER_RIGHT,

        11: vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTH,
        12: vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTH,
        13: vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_WEST,
        14: vg.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_EAST,

        15: vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_TOUCHPAD,
        16: vg.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_TOUCHPAD
    },
}